server:
  port: 18090
spring:
  # Rabbit消费者者配置信息
  rabbitmq:
    # rabbitmq的地址，此处连接的是虚拟机的mq
    host: 192.168.86.168
    # rabbitmq的端口号
    port: 5672
    # rabbitmq管理控制台所创建的虚拟主机
    virtual-host: /libifu
    # rabbitmq管理控制台的登录用户名
    username: libifu
    # rabbitmq管理控制台的登录密码
    password: 123456
    listener:
      # 解决消费堆积，使用多线程消费
      # simple，默认，listener容器使用一个额外线程处理消息；direct，listener（监听器）容器直接使用主线程处理消息
      type: simple
      simple:
        # ack自动确认，manual-手动  auto-自动（无异常直接确认，有异常无限重试） none-不重试
        acknowledge-mode: manual
        # 能者多劳，每次捕获一条消息
        prefetch: 1
        # 避免消息堆积，初始化多个消费者线程（一般是根据电脑的核数来设定）
        concurrency: 4
  # 线程池配置开始
  task:
    # Spring 执行器配置，对应 TaskExecutionProperties 配置类。对于 Spring 异步任务，会使用该执行器。
    execution:
      thread-name-prefix: cart-task- # 线程池的线程名的前缀。默认为 task- ，建议根据自己应用来设置
      pool: # 线程池相关
        core-size: 100 # 核心线程数，线程池创建时候初始化的线程数。默认为 8 。
        max-size: 500 # 最大线程数，线程池最大的线程数，只有在缓冲队列满了之后，才会申请超过核心线程数的线程。默认为 Integer.MAX_VALUE
        keep-alive: 60s # 允许线程的空闲时间，当超过了核心线程之外的线程，在空闲时间到达之后会被销毁。默认为 60 秒
        queue-capacity: 5000 # 缓冲队列大小，用来缓冲执行任务的队列的大小。默认为 Integer.MAX_VALUE 。
        allow-core-thread-timeout: false # 是否允许核心线程超时，即开启线程池的动态增长和缩小。默认为 true 。
      shutdown:
        await-termination: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
        await-termination-period: 60 # 等待任务完成的最大时长，单位为秒。默认为 0 ，根据自己应用来设置
  # 线程池配置结束
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.86.168
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.86.168:3306/guli_cart
    username: root
    password: 123456
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 300000
auth:
  jwt:
    pubKeyPath: D:\Developer_tools\repos\IdeaPros\gmall\rsa\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
    expireTime: 15552000 # userKey的过期时间
mybatis-plus:
  global-config:
    db-config:
      id-type: auto